// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTuXlloqdW5IeVpWQtBUbpaHLppXfJWRM',
    appId: '1:895358631587:web:07c7f9d3954c8edbb90916',
    messagingSenderId: '895358631587',
    projectId: 'shop-c771d',
    authDomain: 'shop-c771d.firebaseapp.com',
    storageBucket: 'shop-c771d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Be6QOBVePs1IgYwCaytgYsSZkQy3VGQ',
    appId: '1:895358631587:android:38c56b7757e57e53b90916',
    messagingSenderId: '895358631587',
    projectId: 'shop-c771d',
    storageBucket: 'shop-c771d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1rBxZnYyQMW2wxn28ZiZucUByT-TEOts',
    appId: '1:895358631587:ios:e6e1193129cbcd42b90916',
    messagingSenderId: '895358631587',
    projectId: 'shop-c771d',
    storageBucket: 'shop-c771d.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
